# Form implementation generated from reading ui file '/home/sand/SandCount.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    counter = 0
    savc = 0
    textset = ""
    restoreto = 67
    canrestore = False
    counter2 = 0
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(828, 409)
        Form.setMinimumSize(QtCore.QSize(828, 409))
        Form.setMaximumSize(QtCore.QSize(828, 409))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/usr/share/sandpotnoodles/sandcount.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.547935, y1:0, x2:0.564, y2:1, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(76, 76, 76, 255));\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(38)
        font.setItalic(True)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(191, 64, 64, 0);")
        self.label.setObjectName("label")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber.setGeometry(QtCore.QRect(10, 70, 541, 161))
        self.lcdNumber.setDigitCount(9)
        self.lcdNumber.setObjectName("lcdNumber")
        self.up = QtWidgets.QPushButton(parent=Form)
        self.up.setGeometry(QtCore.QRect(590, 10, 211, 171))
        self.up.setText("")
        icon = QtGui.QIcon.fromTheme("go-up")
        self.up.setIcon(icon)
        self.up.setIconSize(QtCore.QSize(83, 77))
        self.up.setObjectName("up")
        self.down = QtWidgets.QPushButton(parent=Form)
        self.down.setGeometry(QtCore.QRect(590, 220, 211, 171))
        self.down.setText("")
        icon = QtGui.QIcon.fromTheme("go-down")
        self.down.setIcon(icon)
        self.down.setIconSize(QtCore.QSize(83, 77))
        self.down.setObjectName("down")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(695, 180, 101, 41))
        icon = QtGui.QIcon.fromTheme("edit-undos")
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.reset = QtWidgets.QPushButton(parent=Form)
        self.reset.setGeometry(QtCore.QRect(590, 180, 111, 41))
        icon = QtGui.QIcon.fromTheme("edit-undos")
        self.reset.setIcon(icon)
        self.reset.setIconSize(QtCore.QSize(24, 24))
        self.reset.setObjectName("reset")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=Form)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 250, 541, 141))
        #67
        self.plainTextEdit.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.restore = QtWidgets.QPushButton(parent=Form)
        self.restore.setGeometry(QtCore.QRect(440, 30, 111, 41))
        self.restore.setCheckable(False)
        self.restore.setAutoDefault(False)
        self.restore.setDefault(False)
        self.restore.setFlat(False)
        self.restore.setObjectName("restore")
        self.restore_2 = QtWidgets.QPushButton(parent=Form)
        self.restore_2.setGeometry(QtCore.QRect(330, 30, 111, 41))
        self.restore_2.setCheckable(False)
        self.restore_2.setAutoDefault(False)
        self.restore_2.setDefault(False)
        self.restore_2.setFlat(False)
        self.restore_2.setObjectName("restore_2")
        self.up.clicked.connect(self.goup)
        self.down.clicked.connect(self.godown)
        self.reset.clicked.connect(self.reseter)
        self.pushButton_3.clicked.connect(self.saver)
        self.restore.clicked.connect(self.restorer)
        self.restore_2.clicked.connect(self.clear)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def goup(self):
        self.counter = self.counter+1
        self.lcdNumber.display(self.counter)
    def godown(self):
        self.counter = self.counter-1
        self.lcdNumber.display(self.counter)
    def reseter(self):
        self.canrestore = True
        self.restoreto = self.counter
        self.counter = 0
        self.lcdNumber.display(self.counter)
    def saver(self):
        self.savc = self.savc + 1
        self.textset = f'{self.textset}Saved Result #{self.savc}: {self.counter}\n'
        self.plainTextEdit.setPlainText(self.textset)
    def restorer(self):
        if self.canrestore:
            self.counter2 = self.counter
            self.counter = self.restoreto
            self.restoreto = self.counter2
            self.lcdNumber.display(self.counter)
    def clear(self):
        self.textset = ''
        self.plainTextEdit.setPlainText(self.textset)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "SandCount"))
        self.label.setText(_translate("Form", "SandCount"))
        self.pushButton_3.setText(_translate("Form", "Save"))
        self.restore.setText(_translate("Form", "Restore"))
        self.reset.setText(_translate("Form", "Reset"))
        self.restore_2.setText(_translate("Form", "Clear History"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
